apiVersion: apps/v1 
kind: Deployment
metadata:
  name: genesis
  labels: 
   app: bank
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank
  template:
    metadata:
     labels:
       app: bank
    spec:
      containers:
      - name: cont1
        image: cronosm4m/nileproj:latest