apiVersion: v1 
kind: Service
metadata:
  name: serving-v1
spec:
  type: NodePort
  selector:
    app: bank
  ports:
  - port: 80  #this is for the service
    targetPort: 5000 #this is for the container port.